# Generated by Django 4.0.6 on 2022-07-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_author_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sno',
            new_name='id',
        ),
    ]
