# Generated by Django 4.0.6 on 2022-07-18 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_sno_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='sno',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='timeStamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
